#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x980C197698C3739D (vincent@vinc17.net)
#
Name     : compat-mpfr-soname4
Version  : 3.1.6
Release  : 22
URL      : https://ftp.gnu.org/gnu/mpfr/mpfr-3.1.6.tar.xz
Source0  : https://ftp.gnu.org/gnu/mpfr/mpfr-3.1.6.tar.xz
Source99 : https://ftp.gnu.org/gnu/mpfr/mpfr-3.1.6.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0 LGPL-3.0
Requires: compat-mpfr-soname4-lib
Requires: compat-mpfr-soname4-data
Requires: compat-mpfr-soname4-doc
BuildRequires : gmp-dev
BuildRequires : sed

%description
Contributed by the AriC and Caramba projects, INRIA.
This file is part of the GNU MPFR Library.

%package data
Summary: data components for the compat-mpfr-soname4 package.
Group: Data

%description data
data components for the compat-mpfr-soname4 package.


%package dev
Summary: dev components for the compat-mpfr-soname4 package.
Group: Development
Requires: compat-mpfr-soname4-lib
Requires: compat-mpfr-soname4-data
Provides: compat-mpfr-soname4-devel

%description dev
dev components for the compat-mpfr-soname4 package.


%package doc
Summary: doc components for the compat-mpfr-soname4 package.
Group: Documentation

%description doc
doc components for the compat-mpfr-soname4 package.


%package lib
Summary: lib components for the compat-mpfr-soname4 package.
Group: Libraries
Requires: compat-mpfr-soname4-data

%description lib
lib components for the compat-mpfr-soname4 package.


%prep
%setup -q -n mpfr-3.1.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1514216663
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1514216663
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
%exclude /usr/share/doc/mpfr/AUTHORS
%exclude /usr/share/doc/mpfr/BUGS
%exclude /usr/share/doc/mpfr/COPYING
%exclude /usr/share/doc/mpfr/COPYING.LESSER
%exclude /usr/share/doc/mpfr/FAQ.html
%exclude /usr/share/doc/mpfr/NEWS
%exclude /usr/share/doc/mpfr/TODO
%exclude /usr/share/doc/mpfr/examples/ReadMe
%exclude /usr/share/doc/mpfr/examples/divworst.c
%exclude /usr/share/doc/mpfr/examples/rndo-add.c
%exclude /usr/share/doc/mpfr/examples/sample.c
%exclude /usr/share/doc/mpfr/examples/version.c

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/mpf2mpfr.h
%exclude /usr/include/mpfr.h
%exclude /usr/lib64/libmpfr.so

%files doc
%defattr(-,root,root,-)
%exclude /usr/share/info/mpfr.info

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmpfr.so.4
/usr/lib64/libmpfr.so.4.1.6
